### ISSUE TITLE
Syntax Error in HttpClient.php 

### ISSUE THREAD

**Issue by sperro** [braintree/braintreehttp_php#5]
Using composer I installed Checkout-PHP-SDK which extends BraintreeHttp. 
When verifying the transaction in the GetOrder class I'm getting this error.
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /vendor/braintree/braintreehttp/lib/BraintreeHttp/HttpClient.php on line 38

**Comment by crookedneighbor** [comment]
This repo is no longer maintained by the Braintree team and will be removed shortly.
